hydra:
  output_subdir: null
  run:
    dir: .
  searchpath:
    - pkg://py123d.script.config
    - pkg://py123d.script.config.common
  job:
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths
  - override scene_filter: viser_scenes
  - override execution: thread_pool_executor
  - _self_

logger_level: info  # "debug", "info", "warning", "error"

bokeh_config:
  _target_: py123d.visualization.bokeh.bokeh_config.BokehConfig
  _convert_: 'all'

  # Server
  server_port: 5006

  # BEV
  bev_radius: 80.0

  # Layers
  show_map: true
  show_lidar: true
  show_detections: true
