parser:
  _target_: py123d.parser.nuplan.nuplan_parser.NuplanParser
  _convert_: 'all'

  splits: ["nuplan-mini_train", "nuplan-mini_val", "nuplan-mini_test"]
  nuplan_data_root: ${dataset_paths.nuplan_data_root}
  nuplan_maps_root: ${dataset_paths.nuplan_maps_root}
  nuplan_sensor_root: ${dataset_paths.nuplan_sensor_root}
  log_names:
    - "2021.08.24.13.12.55_veh-45_00386_00472"
    - "2021.10.11.07.12.18_veh-50_00211_00304"

dataset_converter_config:
  _target_: py123d.parser.dataset_converter_config.DatasetConverterConfig
  _convert_: 'all'

  force_log_conversion: ${force_log_conversion}
  force_map_conversion: ${force_map_conversion}
  async_conversion: ${async_conversion}

  # Map
  include_map: true

  # Ego
  include_ego: true

  # Box Detections
  include_box_detections: true

  # Traffic Lights
  include_traffic_lights: true

  # Pinhole Cameras
  include_pinhole_cameras: true
  pinhole_camera_store_option: "path" # "path", "jpeg_binary", "png_binary", "mp4"

  # Lidars
  include_lidars: true
  lidar_store_option: "path" #  "path", "binary"
  lidar_point_cloud_codec: null # None or "laz", "draco", "ipc_zstd", "ipc_lz4", "ipc"
  lidar_point_feature_codec: null # None or "ipc_zstd", "ipc_lz4", "ipc"

  # Scenario tag / Route
  include_scenario_tags: true
  include_route: true

  # Not available:
  include_fisheye_mei_cameras: false

log_writer:
  _target_: py123d.api.scene.arrow.arrow_log_writer.ArrowLogWriter
  _convert_: 'all'
  dataset_converter_config: ${dataset.dataset_converter_config}
  logs_root: ${dataset_paths.py123d_logs_root}
  sensors_root: ${dataset_paths.py123d_sensors_root}
  ipc_compression: null
  ipc_compression_level: null

  sync_config:
    _target_: py123d.api.scene.arrow.arrow_log_writer.SyncConfig
    _convert_: 'all'
    reference_column: lidar.lidar_merged.start_timestamp_us
    direction: "forward" # "forward" or "backward"


map_writer:
  _target_: py123d.api.map.arrow.arrow_map_writer.ArrowMapWriter
  _convert_: 'all'
  force_map_conversion: ${force_map_conversion}
  maps_root: ${dataset_paths.py123d_maps_root}
  logs_root: ${dataset_paths.py123d_logs_root}
